name: Draft Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create_release:
    # Only run this when a release branch was merged into the dev branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Store package version into ENV
        run: echo "VERSION=v$(pnpm pkg get version | tr -d '\"')" >> $GITHUB_ENV
      - name: Generate list of changes
        uses: actions/github-script@v7
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            return commits.map(c => c["message"]).join("\n")
      - name: Create Release Draft
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          artifacts: release/*.tgz
          body: ${{ steps.commit_list.outputs.result }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
      