name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - name: Authenticate to npm registry
        run: |
          echo "@djosar:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Pack
        run: |
          mkdir release
          pnpm pack --pack-destination=release
      - name: Publish
        run: pnpm publish
      - name: Update ENV
        run: echo "VERSION=$(npm pkg get version | tr -d '\"')" >> $GITHUB_ENV
      - name: Create Release Draft
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          artifacts: release/*.tgz
          body: Draft, please replace
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
