name: Release

on:
  workflow_dispatch:
  
jobs:
  create_release_draft:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PNPM Setup
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Authenticate to npm registry
        run: |
          echo "@djosar:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install Dependencies
        run: pnpm install
      - name: Build Project
        run: pnpm build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist
      - name: Create Release Draft
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          artifacts: 'package'
          body: Draft, please replace
          draft: true